### ISSUE TITLE
Two useless notifications?

### ISSUE THREAD

**Issue by leolux** [googlesamples/android-DelayedConfirmation#1]
I noticed that the sample works _exactly_ the same although I remove two notifications from the methods onTimerSelected and onTimerFinished:

```
 @Override
    public void onTimerSelected(View v) {
        v.setPressed(true);
        //Notification notification = new Notification.Builder(this)
          //      .setSmallIcon(R.drawable.ic_launcher)
            //    .setContentTitle(getString(R.string.notification_title))
              //  .setContentText(getString(R.string.notification_timer_selected))
                //.build();
        //((NotificationManager) getSystemService(NOTIFICATION_SERVICE)).notify(0, notification);
        sendMessageToCompanion(TIMER_SELECTED_PATH);
        // Prevent onTimerFinished from being heard.
        ((DelayedConfirmationView) v).setListener(null);
        finish();
    }

    @Override
    public void onTimerFinished(View v) {
        //Notification notification = new Notification.Builder(this)
        //        .setSmallIcon(R.drawable.ic_launcher)
          //      .setContentTitle(getString(R.string.notification_title))
            //    .setContentText(getString(R.string.notification_timer_finished))
              //  .build();
        //((NotificationManager) getSystemService(NOTIFICATION_SERVICE)).notify(0, notification);
        sendMessageToCompanion(TIMER_FINISHED_PATH);
        finish();
    }
```

So the question is: What are those two notifications supposed to do?

**Comment by nbehary** [comment]
The sample doesn't work the same if you remove them.  They post notifications on the Wearable when the timer is selected (while it is running.  It is easy to miss that you have to do it then.) and when it finishes.  

Removing the notification from either stop those notifications from posting in the relevant case.  Otherwise it does behave the same.

**Comment by leolux** [comment]
Good, thank you! I didn't notice the notifications on the Wearable device because they are not visible when the acitivity is on the foreground.
But I have still an issue with the first notification (TIMER_SELECTED_PATH) because it does not appear on my device (SmartWatch3). Only the second notification (TIMER_FINISHED_PATH) appears.

To reproduce:
1. Start wearable activity using handheld button
2. Start timer on the wearable activity
3. close wearable activity
4. Scroll through the notifications -> no notification with "Timer selected" found

**Comment by codingjeremy** [comment]
This sample has been deprecated.
