### ISSUE TITLE
START button does not work

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-DelayedConfirmation#2]
I am running your app on my phone.  I am clicking the START button in the activity.  Absolutely nothing happens. Please advise.

**Comment by IgorGanapolsky** [comment]
You have to add these tags to the activity in the Manifest, otherwise it cannot launch:
      `<activity
            android:name=".MainActivity"
            android:label="@string/app_name">
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="android.intent.category.LAUNCHER"/>
        </activity>`

**Comment by codingjeremy** [comment]
This sample has been deprecated.
